FROM node:5.11.1

MAINTAINER from BUPT by gaoyangyang (gyycoder@gmai.com)

COPY . /gyyzyp/docker_swarm/ui
WORKDIR /gyyzyp/docker_swarm/ui

#install node-gyp
RUN npm i -g node-gyp

#install nodemon
RUN npm install -g nodemon

#install app dependency using package.json
RUN npm install --production

EXPOSE 8100
